# Generated by Django 4.2 on 2025-11-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cajon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('estado', models.CharField(choices=[('FUNCIONAL', 'Funcional'), ('MANTENIMIENTO', 'Mantenimiento')], default='FUNCIONAL', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cajón',
                'verbose_name_plural': 'Cajones',
                'db_table': 'tbl_cajones',
                'ordering': ['numero'],
            },
        ),
    ]
