# Generated by Django 4.2 on 2025-11-13 03:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios.', regex='^[A-Za-zÁÉÍÓÚáéíóúÑñÜü\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido en formato mexicano, con o sin código de país +52.', regex='^(?:\\+52)?\\s?(?:\\(?\\d{2,3}\\)?[\\s-]?)?\\d{7}$')]),
        ),
    ]
